### ISSUE TITLE
[Feature] 拡張機能のアップロード処理実装

### ISSUE THREAD

**Issue by itsu-dev** [tsukuba-cojt/resta#145]
## 概要
拡張機能のアップロード処理を実装する

## 目的
機能実装

## 提案内容
以下を実装する：
1. 拡張機能共有ページ上の `#resta-add-style` ボタンの可視化（`display: block` の挿入）
2. 共有したいスタイルを選択するためのダイアログを実装
3. ボタン押下時にダイアログを表示する
4. 選択されたスタイルを拡張機能共有ページ上の `#resta-style-json`（hidden な input 要素）に注入する

**Comment by itsu-dev** [comment]
そうですね、`#resta-add-style` を押すと拡張機能上のダイアログが表示され、ユーザがダイアログでスタイルを選択したのちに `#resta-style-json` に選択されたスタイルの json が流れ込んでくる仕組みです

**Comment by inaniwaudon** [comment]
良さそう！良いと思います！
