### ISSUE TITLE
[Feature] フォーマットのダウンロードを実装

### ISSUE THREAD

**Issue by K-Kazuyuki** [tsukuba-cojt/resta#152]
## 概要
サイトからフォーマットをダウンロードできるようにする

## 目的
ダウンロードできるようにする

## 提案内容
@K-Kazuyuki が実装すべきことは以下：
- importFormat(downloadUrl: string, title: string, style: string, id: string)
- applyPageFormat(id: string)を実装する
- getImportedFormats(all: boolean  = false): Array<{id: string, title: string, url: string}>

@itsu-dev が実装すべきことは以下：
- テンプレートタブに「インポート済み」タブを生やし、そこから適用できるようにする

@inaniwaudon フロントに実装してほしいことは以下：
- スタイル詳細ページに `#resta-download-style` ボタンを生やし、デフォルトで `display: none` にしておく
- スタイル詳細ページに `#resta-format-json` として `hidden` な input 要素を生やし、`value` にダウンロードさせたい json を格納しておく
- スタイル詳細ページに `#resta-format-title` として `hidden` な input 要素を生やし、`value` にスタイル名を格納しておく
- スタイル詳細ページに `#resta-format-url` として `hidden` な input 要素を生やし、`value` にこのページへの url を格納しておく

**Comment by itsu-dev** [comment]
related to https://github.com/tsukuba-cojt/resta/issues/159
