### ISSUE TITLE
[Bug Report] ボタン、リンクを要素選択するとホバーやクリック時の色がとられる

### ISSUE THREAD

**Issue by K-Kazuyuki** [tsukuba-cojt/resta#158]
## 概要
タイトルの通り

## 具体的な説明
ボタンやリンクを選択し、背景色を確認すると薄い青や赤色という選択時の色が適用される

## 再現手順
ボタンやリンクを選択する

## 期待する動作
リンク文字の元の色である青色やボタンの通常時の色が選択される

**Comment by itsu-dev** [comment]
要素選択方法を変更したので起きなくなった
よって close
