### ISSUE TITLE
[Bug Report] 要素選択の不具合

### ISSUE THREAD

**Issue by K-Kazuyuki** [tsukuba-cojt/resta#201]
## 概要
要素選択で表示に不具合がある

## 具体的な説明
Restaを開いて、要素選択し、閉じると表示が次のようにバグが生じた
https://github.com/tsukuba-cojt/resta/assets/83408581/f4fb5563-fb7d-4cf4-aac3-ebc3922b22c5

## 期待する動作
1つの要素が選択される
また、再度開きなおしても最初と同じように描画される

## 動作環境
必要に応じて以下の内容を記載してください。
- OS とそのバージョン
- Web ブラウザとそのバージョン
- デバイス名
- CPU
- メモリ容量
- ディスプレイサイズ
- 対象の URL

**Comment by itsu-dev** [comment]
@K-Kazuyuki これまで残ってますか？

**Comment by K-Kazuyuki** [comment]
治ってます。
