### ISSUE TITLE
[Feature] 複数の要素選択方法を実装する

### ISSUE THREAD

**Issue by K-Kazuyuki** [tsukuba-cojt/resta#97]
## 概要
現状単一の要素のみしか選択できないため、クラスによる選択など複数の選択方法を実装する

## 目的
複数の要素に分かれているものを一気に変更するため。

## 提案内容
- "シングル"モード
  - 今まで通り単一の要素のみを選択する
- "グループ"モード
  - 同一階層の全ての同じ要素（同じタグ）を選択する
- "スタイル"モード
  - 選択された要素と同じスタイルを持つ要素を選択する

これを行うためには要素の複数選択を実装する必要がある

**Comment by itsu-dev** [comment]
タグ選択モードなどが実装されたため、done とみなして close します
